apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-volume-csi
provisioner: local.volume.csi.kubernetes.io
parameters:
    vgName: volumegroup1
    fsType: ext4
    pvType: localdisk
    lvmType: striping
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
