apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: localvolumes.local.volume.storage
spec:
  additionalPrinterColumns:
    - JSONPath: .status.totalSize
      name: totalSize
      type: string
    - JSONPath: .status.freeSize
      name: freeSize
      type: string
  group: local.volume.storage
  names:
    categories:
      - all
    kind: LocalVolume
    listKind: LocalVolumeList
    plural: localvolumes
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
