apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-volume-csi
