apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm
provisioner: local.volume.csi.kubernetes.io
parameters:
    fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
