apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-volume-csi
provisioner: local.volume.csi.kubernetes.io
parameters:
    vgName: vgtest
    fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
